if [[ $- != *i* ]] ; then
	# Shell is non-interactive.  Be done now!
	return
fi
if [ -f /system/etc/bash/profile ]; then
	source /system/etc/bash/profile
fi
alias lsof='lsof -w'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias ls='ls --color=auto'
alias ll='ls -alF'
alias l='ls -CF'
alias la='ls -A'
alias mv='mv -i'
alias mkdir='mkdir -pv'